


//var databaseName = "pegaSmall";
var databaseName = "test_pega";
var db = db.getSiblingDB(databaseName);

var claimsCol = db.getCollection("claims");

var metaData = {
    "ClaimProperty1":"164900",
    "ClaimProperty2":"0",
    "pxApplication":"Prog",
    "pxApplicationVersion":"01.01.01",
    "pxCommitDateTime":"20191120T162807.387 GMT",
    "pxCoveredCount":"0",
    "pxCoveredCountOpen":"0",
    "pxCoveredCountUnsatisfied":"0",
    "pxCreateDateTime":"20191120T162736.394 GMT",
    "pxCreateOperator":"marik",
    "pxCreateOpName":"Ken Marin",
    "pxCreateSystemID":"sls-envcam84",
    "pxCurrentStage":"PRIM1",
    "pxCurrentStageLabel":"ClaimReview",
    "pxCurrentStageSubscript":"SubSet",
    "pxExternalSystemUpdateCount":"0",
    "pxInsName":"M-771",
    "pxObjClass":"OF2C36-Prog-Work-Marillion",
    "pxSaveDateTime":"20191120T162748.359 GMT",
    "pxUpdateCounter":"2",
    "pxUpdateDateTime":"20191120T162748.359 GMT",
    "pxUpdateOperator":"marik",
    "pxUpdateOpName":"Ken Marin",
    "pxUpdateOrgUnit":"Unit",
    "pxUpdateSystemID":"sls-envcam84",
    "pxUrgencyPartyTotal":"0",
    "pxUrgencyWork":"10",
    "pxUrgencyWorkClass":"10",
    "pxUrgencyWorkStageSLA":"0",
    "pyAgeFromDate":"20191120T162736.395 GMT",
    "pyCaseAssetFormat":"Case secondary content",
    "pyCaseFilter":"Both",
    "pyCaseFilterDescription":"Active Assignments with Subcases",
    "pyConfirmationNote":"pyStepRoutedConfirmation",
    "pyElapsedCustomerUnsatisfied":"11.0",
    "pyElapsedStatusNew":"11.0",
    "pyElapsedStatusOpen":"0",
    "pyElapsedStatusPending":"0",
    "pyFlowKey":"RULE-OBJ-FLOW OF2C36-PROG-WORK-MARILLION PYSTARTCASE #20190729T121530.672 GMT",
    "pyFlowName":"pyStartCase",
    "pyFolderType":"pyDefault",
    "pyID":"M-771",
    "pyInternalAssignmentHandle":"ASSIGN-INTERNAL OF2C36-PROG-WORK M-771!PZINTERNALCASEFLOW",
    "pyLabel":"Marillion",
    "pyLabelOld":"Marillion",
    "pyNextEmailThreadID":"1",
    "pyNotifyQuickStream":"QuestionAboutItem",
    "pyOrigDivision":"Div",
    "pyOrigOrg":"OF2C36",
    "pyOrigOrgUnit":"Unit",
    "pyOrigUserDivision":"Div",
    "pyOrigUserID":"marik",
    "pyOrigUserWorkgroup":"default@OF2C36",
    "pyOwnerDivision":"Div",
    "pyOwnerOrg":"OF2C36",
    "pyOwnerOrgUnit":"Unit",
    "pyParticipantsCount":"0",
    "pyPushNotificationsEnabled":"false",
    "pyRelatedWorkListSize":"0",
    "pyRuleHarness":"RuleForm",
    "pySatisfactionChangeTimestamp":"20191120T162748.301 GMT",
    "pyShowCases":"true",
    "pyShowOpenAssignments":"true",
    "pyStatusCustomerSat":"New",
    "pyStatusWork":"New",
    "pyStatusWorkOld":"New",
    "pyStatusWorkTimestamp":"20191120T162748.301 GMT",
    "pyTemporaryObject":"false",
    "pyWorkIDPrefix":"M-",
    "pyWorkPartiesRule":"pyCaseManagementDefault",
    "pzInsKey":"OF2C36-PROG-WORK M-771",
    "MyAttachment":{ 
	"pxObjClass":"Embed-Attach-File"
    },
    "pxCoveredInsKeys":[ 
	
    ],
    "pxFlow":{ 
	"ClaimReview_Flow":{ 
	    "pxAssignActivity":"WorkList",
	    "pxAssignClass":"Assign-Worklist",
	    "pxAssignmentKey":"ASSIGN-WORKLIST OF2C36-PROG-WORK M-771!ClaimReview_Flow",
	    "pxAssignStatus":"New",
	    "pxFlowInsKey":"RULE-OBJ-FLOW OF2C36-PROG-WORK-MARILLION ClaimReview_Flow #20191011T194024.148 GMT",
	    "pxIsInvestigative":"false",
	    "pxLastUpdateBy":"marik",
	    "pxObjClass":"Embed-PegaEPRO-FlowPage",
	    "pxRouteTo":"marik",
	    "pxRouteToUserName":"Ken Marin",
	    "pxStageFlowID":"FLOW0",
	    "pxSubscript":"ClaimReview_Flow",
	    "pxSystemFlow":"false",
	    "pxTimeFlowStarted":"20191120T162748.183 GMT",
	    "pyCategory":"FlowStandard",
	    "pyConfirmationNote":"pyStepRoutedConfirmation",
	    "pyDeferCommit":"false",
	    "pyDeferErrors":"false",
	    "pyDraftMode":"true",
	    "pyFirstRun":"false",
	    "pyFlowCalledCount":"1",
	    "pyFlowInterestPageClass":"OF2C36-Prog-Work-Marillion",
	    "pyFlowType":"ClaimReview_Flow",
	    "pyFlowTypeLabel":"ClaimReview",
	    "pyIssuedFromStage":"PRIM1",
	    "pyIssuedFromStageLabel":"ClaimReview",
	    "pyIssuedFromStageSubscript":"SubSet",
	    "pyLastFlowStep":"Assignment1",
	    "pyLastFlowStepLabel":"Script for a jester's tear",
	    "pyContexts":{ 
		
	    },
	    "pyFlowParameters":{ 
		"AssignTo":"marik",
		"AutomaticTransition":"false",
		"CurrentflowName":"ClaimReview_Flow",
		"CurrentStage":"PRIM1",
		"CurrentStageLabel":"ClaimReview",
		"CurrentStageSubscript":"SubSet",
		"DoNotEvaluateWhens":"Yes",
		"flowClass":"OF2C36-Prog-Work-Marillion",
		"FlowID":"FLOW0",
		"flowLabel":"ClaimReview",
		"flowName":"ClaimReview_Flow",
		"flowType":"ClaimReview_Flow",
		"isThisReEntry":"No",
		"pyCaseTypePurpose":"STAGE_STARTPROCESSES",
		"pyForEachCount":"1",
		"pyProcessPageName":"pySupportProcessList",
		"pySubCasesPageName":"pySubCasesList",
		"ReferencePageName":"pyWorkPage"
	    },
	    "pyFlowPath":[ 
		{ 
		    "pxObjClass":"Embed-PegaEPRO-FlowPath",
		    "pyDisplay":"true",
		    "pyFAProcessOnJump":"false",
		    "pyFlowStep":"Assignment1",
		    "pyStepLabel":"Script for a jester's tear",
		    "pyStepType":"ASSIGNMENT"
		}
	    ]
	},
	"pzInternalCaseFlow":{ 
	    "pxAssignActivity":"pzCreateInternalAssignment",
	    "pxAssignClass":"Assign-Internal",
	    "pxAssignIsVirtual":"true",
	    "pxAssignmentKey":"ASSIGN-INTERNAL OF2C36-PROG-WORK M-771!PZINTERNALCASEFLOW",
	    "pxFlowInsKey":"RULE-OBJ-FLOW WORK- PZINTERNALCASEFLOW #20180713T133112.404 GMT",
	    "pxIsInvestigative":"false",
	    "pxLastUpdateBy":"marik",
	    "pxObjClass":"Embed-PegaEPRO-FlowPage",
	    "pxRouteTo":"default@of2c36",
	    "pxSubscript":"pzInternalCaseFlow",
	    "pxSystemFlow":"true",
	    "pxTimeFlowStarted":"20191120T162747.843 GMT",
	    "pyCategory":"FlowStandard",
	    "pyDeferCommit":"false",
	    "pyDeferErrors":"false",
	    "pyDraftMode":"false",
	    "pyFirstRun":"false",
	    "pyFlowCalledCount":"1",
	    "pyFlowInterestPageClass":"OF2C36-Prog-Work-Marillion",
	    "pyFlowType":"pzInternalCaseFlow",
	    "pyFlowTypeLabel":"Internal flow",
	    "pyLastFlowStep":"ASSIGNMENT63",
	    "pyLastFlowStepLabel":"Perform action",
	    "pyContexts":{ 
		
	    },
	    "pyFlowParameters":{ 
		"AssignTo":"default@of2c36",
		"flowName":"pzInternalCaseFlow",
		"isNewCase":"true",
		"ReferencePageName":"pyWorkPage"
	    },
	    "pyFlowPath":[ 
		{ 
		    "pxObjClass":"Embed-PegaEPRO-FlowPath",
		    "pyDisplay":"false",
		    "pyFAProcessOnJump":"false",
		    "pyFlowStep":"ASSIGNMENT63",
		    "pyStepLabel":"Perform action",
		    "pyStepType":"ASSIGNMENT"
		}
	    ]
	}
    },
    "pxStageHistory":[ 
	{ 
	    "pxEnterStageTime":"20191120T162747.925 GMT",
	    "pxObjClass":"Embed-StageHistory",
	    "pxStageID":"PRIM1",
	    "pxStageName":"ClaimReview",
	    "pxStageType":"Primary",
	    "pxSubscript":"SubSet",
	    "pxProcesses":[ 
		{ 
		    "pxFlowID":"FLOW0",
		    "pxIsComplete":"False",
		    "pxIsOptional":"false",
		    "pxObjClass":"Embed-StageProcessHistory",
		    "pxProcessName":"ClaimReview_Flow",
		    "pxStartedBy":"Ken Marin",
		    "pxStartTime":"20191120T162747.986 GMT",
		    "pxSubscript":"ClaimReview_Flow",
		    "pyLabel":"ClaimReview",
		    "pxSteps":[ 
			{ 
			    "pxObjClass":"Embed-StageStepHistory",
			    "pxStepID":"Assignment1",
			    "pxStepType":"ASSIGNMENT",
			    "pyLabel":"Script for a jester's tear"
			}
		    ]
		}
	    ]
	}
    ],
    "pxSystemUpdateDetailsList":[ 
    ],
    "pyAttachmentCategories":[ 
    ],
    "pyCaseRelatedContent":[ 
    ],
    "pyFields":[ 
	{ 
	    "pxCreateDateTime":"20190729T122436.513 GMT",
	    "pxInsId":"!ITSTIME",
	    "pxInsName":"OF2C36-PROG-WORK-MARILLION!ITSTIME",
	    "pxObjClass":"Embed-Fields",
	    "pyCalculationClass":"OF2C36-Prog-Work-Marillion",
	    "pyClassName":"OF2C36-Prog-Work-Marillion",
	    "pyDynaUILabel":"ItsTime",
	    "pyDynaUIPropertyReferenceTime":"164900",
	    "pyFunctionHelperText":"Use '.' (dot) for field prompts to enter a simple equation such as:.Amount*.Quantity",
	    "pyHasExpression":"false",
	    "pyHTMLControl":"pxDateTime",
	    "pyIsCalculationEditable":"true",
	    "pyIsCalculationSimple":"true",
	    "pyIsFieldControlReadOnly":"false",
	    "pyIsFieldForWorkClass":"true",
	    "pyIsReference":"false",
	    "pyIsSpecial":"false",
	    "pyIsSystemField":"false",
	    "pyLabel":"ItsTime",
	    "pyMaxLength":"0",
	    "pyModeCalc":"false",
	    "pyModeReadOnly":"false",
	    "pyPicklistControlType":"pxDateTime",
	    "pyPicklistSourcingType":"Local",
	    "pyPropertyMode":"String",
	    "pyPropertyName":"ItsTime",
	    "pyPropertyType":"TimeOfDay:pxDateTime",
	    "pyPxInsName":"OF2C36-PROG-WORK-MARILLION!ITSTIME",
	    "pyRelevantClass":"OF2C36-Prog-Work-Marillion",
	    "pyRelevantClassLabel":"Marillion",
	    "pyRuleSet":"Prog",
	    "pyRuleSetVersion":"01-01-01",
	    "pyStreamName":"pxDateTime",
	    "pyStringType":"TimeOfDay",
	    "pyTableIsDisplayOnly":"false",
	    "pyTempDataClassLabel":"Marillion",
	    "pzInsKey":"RULE-OBJ-PROPERTY OF2C36-PROG-WORK-MARILLION ITSTIME #20190729T122436.513 GMT"
	},
	{ 
	    "pxCreateDateTime":"20190801T125500.493 GMT",
	    "pxInsId":"!MYATTACHMENT",
	    "pxInsName":"OF2C36-PROG-WORK-MARILLION!MYATTACHMENT",
	    "pxObjClass":"Embed-Fields",
	    "pyAutoPopulate":"true",
	    "pyCategory":"Design",
	    "pyCategoryName":"Design",
	    "pyClassName":"OF2C36-Prog-Work-Marillion",
	    "pyDataClass":"Embed-Attach-File",
	    "pyDataClassLabel":"Attachment",
	    "pyDataPageLabel":"D_AttachmentFieldInfo",
	    "pyDataPageName":"D_AttachmentFieldInfo",
	    "pyDynaUILabel":"myAttachment",
	    "pyDynaUIPageReference":"pyWorkPage.MyAttachment",
	    "pyDynaUISectionReference":"pyAttachFieldOptional",
	    "pyHTMLControl":"Attachment",
	    "pyIsFieldControlReadOnly":"false",
	    "pyIsFieldForWorkClass":"true",
	    "pyIsNonRefAutoProperty":"false",
	    "pyIsReference":"true",
	    "pyIsSpecial":"false",
	    "pyIsSystemField":"false",
	    "pyLabel":"myAttachment",
	    "pyModeCalc":"false",
	    "pyPageClass":"Embed-Attach-File",
	    "pyPropertyMode":"Page",
	    "pyPropertyName":"MyAttachment",
	    "pyPropertyType":"Page:Attachment",
	    "pyPxInsName":"OF2C36-PROG-WORK-MARILLION!MYATTACHMENT",
	    "pyRelevantClass":"OF2C36-Prog-Work-Marillion",
	    "pyRelevantClassLabel":"Marillion",
	    "pyRuleSet":"Prog",
	    "pyRuleSetVersion":"01-01-01",
	    "pyStreamName":"Attachment",
	    "pyStringType":"Page",
	    "pyTempDataClassLabel":"Marillion",
	    "pyUsesOldAutoPopulate":"false",
	    "pzInsKey":"RULE-OBJ-PROPERTY OF2C36-PROG-WORK-MARILLION MYATTACHMENT #20190801T125500.493 GMT",
	    "pyDOKeyList":[ 
		
	    ],
	    "pyDOParamList":[ 
		{ 
		    "pxObjClass":"Embed-NameValuePair",
		    "pyDescription":"Attachment Field Name",
		    "pyName":"AttachmentFieldName",
		    "pyParameterRequired":"-1",
		    "pyValue":"\"MyAttachment\""
		},
		{ 
		    "pxObjClass":"Embed-NameValuePair",
		    "pyDescription":"Ins Key of the case",
		    "pyName":"LinkRefFrom",
		    "pyParameterRequired":"0",
		    "pyValue":".pzInsKey"
		},
		{ 
		    "pxObjClass":"Embed-NameValuePair",
		    "pyDescription":"Category of the attachment",
		    "pyName":"AttachmentCategory",
		    "pyParameterRequired":"0",
		    "pyValue":"\"Design\""
		},
		{ 
		    "pxObjClass":"Embed-NameValuePair",
		    "pyDescription":"Class Name",
		    "pyName":"ClassName",
		    "pyParameterRequired":"0",
		    "pyValue":".pxObjClass"
		},
		{ 
		    "pxObjClass":"Embed-NameValuePair",
		    "pyDescription":"Case ID",
		    "pyName":"CaseID",
		    "pyParameterRequired":"0",
		    "pyValue":".pyID"
		}
	    ]
	},
	{ 
	    "pxCreateDateTime":"20191011T193325.860 GMT",
	    "pxInsId":"!HEKNOWSYOUKNOW",
	    "pxInsName":"OF2C36-PROG-WORK-MARILLION!HEKNOWSYOUKNOW",
	    "pxObjClass":"Embed-Fields",
	    "pyCalculationClass":"OF2C36-Prog-Work-Marillion",
	    "pyClassName":"OF2C36-Prog-Work-Marillion",
	    "pyDynaUILabel":"He knows you know",
	    "pyFunctionHelperText":"Use '.' (dot) for field prompts to enter a simple equation such as:.Amount*.Quantity",
	    "pyHasExpression":"false",
	    "pyHTMLControl":"pxTextInput",
	    "pyIsCalculationEditable":"true",
	    "pyIsCalculationSimple":"true",
	    "pyIsFieldControlReadOnly":"false",
	    "pyIsFieldForWorkClass":"true",
	    "pyIsReference":"false",
	    "pyIsSpecial":"false",
	    "pyIsSystemField":"false",
	    "pyLabel":"He knows you know",
	    "pyMaxLength":"0",
	    "pyModeCalc":"false",
	    "pyModeReadOnly":"false",
	    "pyPicklistControlType":"pxTextInput",
	    "pyPicklistSourcingType":"Local",
	    "pyPropertyMode":"String",
	    "pyPropertyName":"HeKnowsYouKnow",
	    "pyPropertyType":"Text:pxTextInput",
	    "pyPxInsName":"OF2C36-PROG-WORK-MARILLION!HEKNOWSYOUKNOW",
	    "pyRelevantClass":"OF2C36-Prog-Work-Marillion",
	    "pyRelevantClassLabel":"Marillion",
	    "pyRuleSet":"Prog",
	    "pyRuleSetVersion":"01-01-01",
	    "pyStreamName":"pxTextInput",
	    "pyStringType":"Text",
	    "pyTableIsDisplayOnly":"false",
	    "pyTempDataClassLabel":"Marillion",
	    "pzInsKey":"RULE-OBJ-PROPERTY OF2C36-PROG-WORK-MARILLION HEKNOWSYOUKNOW #20191011T193325.860 GMT"
	},
	{ 
	    "pxCreateDateTime":"20191011T193343.592 GMT",
	    "pxInsId":"!THEWEB",
	    "pxInsName":"OF2C36-PROG-WORK-MARILLION!THEWEB",
	    "pxObjClass":"Embed-Fields",
	    "pyCalculationClass":"OF2C36-Prog-Work-Marillion",
	    "pyClassName":"OF2C36-Prog-Work-Marillion",
	    "pyDynaUILabel":"The web",
	    "pyFunctionHelperText":"Use '.' (dot) for field prompts to enter a simple equation such as:.Amount*.Quantity",
	    "pyHasExpression":"false",
	    "pyHTMLControl":"pxTextInput",
	    "pyIsCalculationEditable":"true",
	    "pyIsCalculationSimple":"true",
	    "pyIsFieldControlReadOnly":"false",
	    "pyIsFieldForWorkClass":"true",
	    "pyIsReference":"false",
	    "pyIsSpecial":"false",
	    "pyIsSystemField":"false",
	    "pyLabel":"The web",
	    "pyMaxLength":"0",
	    "pyModeCalc":"false",
	    "pyModeReadOnly":"false",
	    "pyPicklistControlType":"pxTextInput",
	    "pyPicklistSourcingType":"Local",
	    "pyPropertyMode":"String",
	    "pyPropertyName":"TheWeb",
	    "pyPropertyType":"Text:pxTextInput",
	    "pyPxInsName":"OF2C36-PROG-WORK-MARILLION!THEWEB",
	    "pyRelevantClass":"OF2C36-Prog-Work-Marillion",
	    "pyRelevantClassLabel":"Marillion",
	    "pyRuleSet":"Prog",
	    "pyRuleSetVersion":"01-01-01",
	    "pyStreamName":"pxTextInput",
	    "pyStringType":"Text",
	    "pyTableIsDisplayOnly":"false",
	    "pyTempDataClassLabel":"Marillion",
	    "pzInsKey":"RULE-OBJ-PROPERTY OF2C36-PROG-WORK-MARILLION THEWEB #20191011T193343.592 GMT"
	}
    ],
    "pyRelatedWorkList":[ 
    ],
    "pyRulePage":{ 
	
    },
    "pyWorkParty":{ 
	
    }
}


claimsCol.updateMany({"Meta" : {$exists: false}},
		    {$set : {"Meta" : metaData}}
		   );
