version: '3'

services:
  zookeeper:
    image: debezium/zookeeper:0.9
    expose:
      - 2181
      - 2888
      - 3888

  kafka:
    image: debezium/kafka:0.9
    expose:
      - 9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  mongodb:
    image: mongo:4.1.7
    expose:
      - 27017
    environment:
      - MONGODB_USER=cleanroom
      - MONGODB_PASSWORD=cleanroom

  mongosetup:
    image: mongo:4.1.7
    depends_on:
      - mongodb
    volumes:
      - ./setup-mongodb.sh:/setup-mongodb.sh
      - ./sampleMembers.json:/sampleMembers.json
    restart: always
    entrypoint: [ "bash", "/setup-mongodb.sh" ]


  redis:
    image: redis:5.0.3
    expose:
      - 6379

  etl:
    image: pega/etl:1
    links:
      - kafka
      - redis
      - mongodb
    environment:
      - REDIS=redis://redis:6379
      - KAFKA=kafka:9092
      - MONGO_HOST=mongodb
      - MONGO_USER=cleanroom
      - MONGO_PASSWORD=cleanroom
      - MONGO_DATABASE_NAME=cleanroom
      - MONGO_AUTHENTICATION_DATABASE=admin

  oms:
    image: pega/oms-spring:1
    expose:
      - 1234
    links:
      - kafka
      - redis
    environment:
      - KAFKA=kafka:9092
      - REDIS=redis://redis:6379
      - RESOURCES=member

  data-service:
    image: pega/data-service:1
    ports:
      - 8080:8080
    links:
      - oms
      - redis
    environment:
      - REDIS=redis://redis:6379
      - OMS=http://oms:1234

